---
title: "immdonor"
output: rmarkdown::github_document

---

```{r setup, include=FALSE}
library(flowWorkspace)
library(flowCore)
library(ImmPortR)
library(dplyr)
library(stringr)
library(openCyto)
library(MetaCyto)
library(immdonor)

SDY702<- donor_search(study = "SDY702")
SDY1097<- donor_search(study = "SDY1097")
meta<- rbind(SDY702,SDY1097)

tcell<- panel_parser(donorMeta = meta)

```

Installation
```{r eval=FALSE}
devtools::install_github("mrj31/immdonor")
```

Search for donors in SDY702 and SDY1097
```{r }
SDY702<- donor_search(study = "SDY702")
SDY1097<- donor_search(study = "SDY1097")
```

Parse fcs headers 
```{r }
meta<- rbind(SDY702,SDY1097)
donormeta<- panel_parser(donorMeta = meta)
```


```{r echo=FALSE}
subjects<- unique(donormeta$subjectAccession)
samples<-  donormeta %>% group_by(biosampleType) %>% count(biosampleType)
subjects
samples
```

```{r echo=FALSE}

fcs<- donormeta %>%
  dplyr::filter(!str_detect(fileName, "Surface"))

donormeta$fcs_files<- donormeta$filePath
donormeta$study_id <- donormeta$biosampleType

fcs<- donormeta %>%
  dplyr::filter(panel_id == "FCM-2" | panel_id == "FCM-3")


fcs_info<- fcs %>% 
  dplyr::select("fcs_files", "study_id")

sample_info<- fcs %>% 
  dplyr::select("fcs_files", "gender","maxSubjectAge")

cs<- load_cytoset(path = "cytosets/fcstrans/CD28CD31CD127")

```

Preprocess
```{r}
preprocessing.batch(inputMeta = fcs_info,
                    assay = "FCM",
                    outpath = "metacyto/2052/preprocess_output",
                    b = 1/150,
                    excludeTransformParameters=c("FSC-A","FSC-W","FSC-H","SSC-A","SSC-W","SSC-H","Time"))
```


```{r echo = FALSE}
# collect preprocessing information
files=list.files("metacyto/2052",pattern="processed_sample",recursive=TRUE,full.names=TRUE)
panel_info=collectData(files,longform=FALSE)

# analyze the panels
PS=panelSummary(panelInfo = panel_info,
                folder = "metacyto/2052",
                cluster=FALSE,
                width=40,
                height=30)


new<- markernames(cs)

channels_to_exclude <- c(grep(colnames(cs), pattern="FSC"),
                         grep(colnames(cs), pattern="SSC"),
                         grep(colnames(cs), pattern="Time"))
old <- colnames(cs)[-channels_to_exclude]
old<- toupper(old)
oldplus<-paste0(old,"+")
oldminus<-paste0(old,"-")

nameUpdator(oldNames=old, newNames=new, files=files)
nameUpdator(oldNames=oldplus, newNames=new, files=files)
nameUpdator(oldNames=oldminus, newNames=new, files=files)

```
Identify and Label clusters 
```{r}
#define parameters that we don't want to cluster
excludeClusterParameters=c("FSC-A","FSC-W","FSC-H","SSC-A","SSC-W","SSC-H","Time")

cluster_label=autoCluster.batch(preprocessOutputFolder="metacyto/2052/preprocess_output",
                                excludeClusterParameters=excludeClusterParameters,
                                labelQuantile=0.95,
                                minPercent = 0.05,
                                clusterFunction=flowSOM.MC)
```

Search for clusters
```{r}
searchCluster.batch(preprocessOutputFolder="metacyto/2052/preprocess_output",
                    outpath="metacyto/2052/search_output",
                    clusterLabel=cluster_label)
```


General Analysis
```{r}
# Collect Summary statistics generated in step 3
files=list.files("metacyto/2052/search_output",pattern="cluster_stats_in_each_sample",recursive=TRUE,full.names=TRUE)
fcs_stats=collectData(files,longform=TRUE)

# join the cluster summary statistics with sample information
all_data=inner_join(fcs_stats,sample_info,by="fcs_files")

# See the fraction of what clusters are affected by age (while controlling for Gender)
GA=glmAnalysis(value="value",variableOfInterst="maxSubjectAge",parameter="fraction",
               otherVariables=c("gender"),studyID="study_id",label="label",
               data=all_data,CILevel=0.95,ifScale=c(TRUE,FALSE))
GA=GA[order(GA$Effect_size),]

GA$label=as.character(GA$label)
w = which(nchar(GA$label)<30)
GA = GA[w,]

# plot the results
plotGA(GA, size = 8)
```

