---
title: "cytoqc"
output: html_document
---

```{r global, include=FALSE}
library(flowCore)
library(flowWorkspace)
library(ImmPortR)
library(dplyr)
library(stringr)
library(openCyto)
library(MetaCyto)
library(kableExtra)
library(cytoqc)
source("R/donor_search.r")
source("R/panel_parser.R")


SDY702<- donor_search(study = "SDY702")
SDY1097<- donor_search(study = "SDY1097")
meta<- rbind(SDY702,SDY1097)

df<- panel_parser(donorMeta = meta)

fcs<- df %>%
  dplyr::filter(panel_id == "FCM-2"|panel_id == "FCM-3"|panel_id == "FCM-29")


files<- fcs$fcs_files

cqc_data <- cqc_load_fcs(files)
cqc_data
```

Channels
```{r}

channel_groups <- cqc_check(cqc_data, type = "channel")
summary(channel_groups)

```



Markers
```{r}
marker_groups <- cqc_check(cqc_data,type = "marker")
summary(marker_groups)


panel_groups <- cqc_check(cqc_data, type = "panel", by = "marker")
summary(panel_groups)

cqc_data[1]

solution <-  cqc_match(marker_groups, ref = 2, )
solution

solution <- cqc_update_match(solution, map = c("apc cd33" = "CD33 APC"))
solution

cqc_fix(solution)
solution

solution <- cqc_update_match(solution, map = c(NULL = "CD28"))
solution

groups <- cqc_check(cqc_data, "marker")
groups
```

