---
title: "SDY702/1097"
output: html_document
---
```{r global, include=FALSE}

library(flowCore)
library(flowWorkspace)
library(ImmPortR)
library(tidyverse)
library(openCyto)
library(MetaCyto)
library(ggcyto)
library(kableExtra)
library(plotly)
library(cytoqc)
source("R/donor_search.r")
source("R/panel_parser.R")


SDY702<- donor_search(study = "SDY702")
SDY1097<- donor_search(study = "SDY1097")
immport<- rbind(SDY702,SDY1097)
donormeta<- panel_parser(donorMeta = immport)
files<- donormeta$fcs_files
df<-donormeta
```

```{r}
fcs<- df %>%
  dplyr::filter(panel_id == "FCM-2"|panel_id == "FCM-3"|panel_id == "FCM-5"|panel_id == "FCM-6"|panel_id == "FCM-7"|panel_id == "FCM-29")

fcs<- fcs %>%
  dplyr::filter(biosampleType == "Lung"|biosampleType == "Lung lymph node"|biosampleType == "Spleen"|biosampleType == "Whole blood"|biosampleType == "PBMC")

fcs$study_id <- fcs$biosampleType

fcs_info<- fcs %>% 
  dplyr::select("fcs_files", "study_id")

sample_info<- fcs %>% 
  dplyr::select("fcs_files","biosampleType", "gender","maxSubjectAge")

preprocessing.batch(inputMeta = fcs_info,
                    assay = "FCM",
                    outpath = "metacyto/panel/preprocess_output",
                    b = 1/150,
                    excludeTransformParameters=c("FSC-A","FSC-W","FSC-H","SSC-A","SSC-W","SSC-H","Time"))

files=list.files("metacyto/panel",pattern="processed_sample",recursive=TRUE,full.names=TRUE)
cs<- load_cytoset(path = "R/cytosets/fcstrans/FCM2FCM3")
new<- markernames(cs)
channels_to_exclude <- c(grep(colnames(cs), pattern="FSC"),
                         grep(colnames(cs), pattern="SSC"),
                         grep(colnames(cs), pattern="Time"))
old <- colnames(cs)[-channels_to_exclude]
old<- toupper(old)
oldplus<-paste0(old,"+")
oldminus<-paste0(old,"-")

nameUpdator(oldNames=old, newNames=new, files=files)
nameUpdator(oldNames=oldplus, newNames=new, files=files)
nameUpdator(oldNames=oldminus, newNames=new, files=files)


#define parameters that we don't want to cluster-CD31,CD28,CD127
excludeClusterParameters=c("FSC-A","FSC-W","FSC-H","SSC-A","SSC-W","SSC-H","Time","CD31","CD28","CD127")

cluster_label=autoCluster.batch(preprocessOutputFolder="metacyto/panel/preprocess_output",
                                excludeClusterParameters=excludeClusterParameters,
                                labelQuantile=0.95,
                                minPercent = 0.05,
                                clusterFunction=flowSOM.MC)

searchCluster.batch(preprocessOutputFolder="metacyto/panel/preprocess_output",
                    outpath="metacyto/panel/search_output",
                    clusterLabel=cluster_label)


files=list.files("metacyto/panel/search_output",pattern="cluster_stats_in_each_sample",recursive=TRUE,full.names=TRUE)
fcs_stats=collectData(files,longform=TRUE)

# join the cluster summary statistics with sample information
all_data=inner_join(fcs_stats,sample_info,by="fcs_files")

# See the fraction of what clusters are affected by age (while controlling for Gender)
GA=glmAnalysis(value="value",variableOfInterst="biosampleType",parameter="fraction",
               otherVariables=c("gender","maxSubjectAge"),studyID="study_id",label="label",
               data=all_data,CILevel=0.95,ifScale=c(TRUE,FALSE))

GA=GA[order(GA$`Effect_size`),]

GA$`label`=as.character(GA$`label`)
w = which(nchar(GA$`label`)<30)
GA<- GA[w,]
```


```{r,fig.height = 30, fig.width= 7}
# plot the results
plotGA(GA, size = 12)
 ```
 
 